name: Build
on:
  repository_dispatch:
    types: update-build

jobs:
  build:
    name: Build
    env:
      GOPATH: /home/runner/work/wg-easy-vpn/wg-easy-vpn/go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: go/src/wg-easy-vpn

      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.1'
      
      - name: Install packages
        uses: mstksg/get-package@v1
        with:
          apt-get: software-properties-common byacc flex dpkg-dev debhelper crossbuild-essential-armel crossbuild-essential-armhf crossbuild-essential-arm64
      
      - name: Get dependencies
        working-directory: go/src/wg-easy-vpn
        run: |
          env | grep GO
          go env
          pwd
          ls -al
          make deps

      - name: Build binaries
        working-directory: go/src/wg-easy-vpn
        run: |
          make GOARCH=amd64
          make GOARCH=arm64
          make GOARCH=arm GOARM=7
        
      - name: Create debian packages
        working-directory: go/src/wg-easy-vpn
        run: |
          make doc
          make debian-no-sign GOARCH=amd64
          make debian-no-sign GOARCH=arm64
          make debian-no-sign GOARCH=arm GOARM=7

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: wg-easy-vpn-bin
          path: go/src/wg-easy-vpn/bin/
      
      - name: Upload debian packages
        uses: actions/upload-artifact@v1
        with:
          name: wg-easy-vpn-deb
          path: go/src/wg-easy-vpn/dist/
