name: Build
on:
  repository_dispatch:
    types: update

jobs:
  build:
    name: Build all
    # env:
    #   GOPATH: /home/runner/work/wg-easy-vpn/wg-easy-vpn/go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: go/src/wg-easy-vpn

      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.1' # The Go version to download (if necessary) and use.
      
      - name: Install packages
        uses: mstksg/get-package@v1
        with:
          apt-get: software-properties-common byacc flex dpkg-dev debhelper crossbuild-essential-armel crossbuild-essential-armhf crossbuild-essential-arm64
      
      - name: Debug
        run: |
          env | grep GO
          go env
          pwd
          ls -al
          make deps

      - run: make
      # - name: Set up Go 1.14.1
      #   uses: actions/setup-go@v1
      #   with:
      #     go-version: 1.14.1
      #   id: go

      # - name: Check out code into the Go module directory
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 1
      #     path: go/src/wg-easy-vpn

      # - name: Debug
      #   # env:
      #   #   GOPATH: $PATH
      #   run: |
      #     env | grep GO
      #     go env
      #     pwd
      #     ls -al
        
      # - name: Install packages
      #   uses: mstksg/get-package@v1
      #   with:
      #     apt-get: $PACKAGES

      # - name: Get dependencies
      #   # env:
      #   #   GOPATH: $PATH
      #   run: |
      #     pwd
      #     ls -al
      #     cd $GOPATH/src/wg-easy-vpn
      #     make deps
      #   working-directory: $GOPATH/src/wg-easy-vpn
      
      # - name: Build binaries
      #   # env:
      #   #   GOPATH: /home/runner/work/wg-easy-vpn/wg-easy-vpn/go
      #   run: |
      #     pwd
      #     debhelper
      #     make GOARCH=amd64
      #     make GOARCH=arm64
      #     make GOARCH=arm GOARM=7
      #   working-directory: $GOPATH/src/wg-easy-vpn
    
      # - name: Create debian packages
      #   # env:
      #     # GOPATH: /home/runner/work/wg-easy-vpn/wg-easy-vpn/go
      #   run: |
      #     make debian GOARCH=amd64
      #     make debian GOARCH=arm64
      #     make debian GOARCH=arm GOARM=7
      #   working-directory: $GOPATH/src/wg-easy-vpn

    #   - name: Upload binaries
    #     uses: actions/upload-artifact@v1
    #     with:
    #       name: netspot
    #       path: bin/


    #   - name: Upload debian package
    #     uses: actions/upload-artifact@v1
    #     with:
    #       name: netspot-debian-amd64
    #       path: dist/debian/