name: Test
on:
  repository_dispatch:
    types: update-test

jobs:
  test:
    name: Test
    env:
      GOPATH: /home/runner/work/wg-easy-vpn/wg-easy-vpn/go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: go/src/wg-easy-vpn

      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.1'

      - name: Run Unit tests.
        run: make deps; make cover
        working-directory: go/src/wg-easy-vpn
      
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: go/src/wg-easy-vpn/coverage.txt