name: Test

on:
  push:

jobs:
  test:
    name: Test
    env:
      GOPATH: /home/runner/work/wg-easy-vpn/wg-easy-vpn/go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
      - name: Test
        run: make test
        env:
          # see https://stackoverflow.com/a/79780883
          GOTOOLCHAIN: go1.25.5+auto
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}