// vpn.go
//
//

package models

import (
	"context"
	"fmt"
	"net"
	"strings"

	"github.com/asiffer/wg-easy-vpn/crypto"
	"github.com/asiffer/wg-easy-vpn/utils"
	"github.com/rs/zerolog"
)

// WGVPN denotes a Wireguard VPN (one server and several clients)
type WGVPN struct {
	name     string            // name of the connection
	server   *WGServer         // server
	peers    []*WGClientAsPeer // clients
	dns      []net.IP          // common config
	endpoint string            // common config
	networks []net.IPNet       // common config
	routes   []net.IPNet       // common config
}

func NewWGVPN(name string, server *WGServer, endpoint string, networks []net.IPNet, dns []net.IP, routes []net.IPNet) (*WGVPN, error) {
	vpn := &WGVPN{
		name:     name,
		server:   server,
		peers:    make([]*WGClientAsPeer, 0),
		dns:      dns,
		endpoint: endpoint,
		networks: networks,
		routes:   routes,
	}
	// provide address to the server
	networks, err := vpn.ProvideNetworks()
	if err != nil {
		return nil, err
	}

	vpn.server.address = append(vpn.server.address, networks...)
	return vpn, nil
}

func VPNFromFile(name string, cfg *utils.File) (*WGVPN, error) {
	// Read server/node
	vpn := WGVPN{
		name:   name,
		server: nil,
		peers:  make([]*WGClientAsPeer, 0),
	}

	for _, sec := range cfg.Sections() {
		switch sec.Name() {
		case "Interface":
			server, err := ServerFromSection(sec)
			if err != nil {
				return nil, err
			}
			vpn.server = server
		case "Peer":
			peer, err := PeerFromSection(sec)
			if err != nil {
				return nil, err
			}
			if peer != nil {
				vpn.peers = append(vpn.peers, peer)
				// peers = append(peers, peer)
			}
		case utils.DEFAULT_SECTION:
			// name, err := sec.Get("Name")
			// if err != nil {
			// 	// name is mandatory
			// 	return nil, err
			// }
			// vpn.name = name
			dns, err := sec.GetIPArray("DNS")
			if err == nil {
				vpn.dns = dns
			}
			endpoint, err := sec.Get("Endpoint")
			if err == nil {
				vpn.endpoint = endpoint
			}
			networks, err := sec.GetNetworks("Network")
			if err == nil {
				vpn.networks = networks
			}
			routes, err := sec.GetNetworks("Routes")
			if err == nil {
				vpn.routes = routes
			}
		default:
			// non-blocking
		}
	}

	return &vpn, nil
}

// NumberOfPeers returns the number of clients in the vpn
func (vpn *WGVPN) NumberOfPeers() int {
	return len(vpn.peers)
}

// RemovePeer does what it says
func (vpn *WGVPN) RemovePeer(k crypto.Key) error {
	for i, p := range vpn.peers {
		if k.Base64() == p.Public() {
			vpn.peers = append(vpn.peers[:i], vpn.peers[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("this peer (%s) is not in the VPN", k.Base64())
}

// PopulateServer write the vpn config into a file (server conf only)
func (vpn *WGVPN) PopulateServer(f *utils.File) {
	section := f.AddSection("Interface")
	vpn.server.Populate(section)

	for _, peer := range vpn.peers {
		section = f.AddSection("Peer")
		peer.Populate(section)
	}
}

// Populate writes the full vpn config into a file
func (vpn *WGVPN) Populate(f *utils.File) {
	def := f.GetorCreateSection(utils.DEFAULT_SECTION)
	def.AddComment("The top-level config is generated by wg-easy-vpn")
	def.AddComment("It is ignored by wireguard (wg, wg-quick, etc.)")
	// def.Set("Name", vpn.name)
	def.Set("Endpoint", vpn.endpoint)
	if len(vpn.dns) > 0 {
		def.Set("DNS", strings.Join(utils.StringifyIPs(vpn.dns), ","))
	}
	if len(vpn.networks) > 0 {
		def.Set("Network", strings.Join(utils.StringifyNetworks(vpn.networks), ","))
	}
	if len(vpn.routes) > 0 {
		def.Set("Routes", strings.Join(utils.StringifyNetworks(vpn.routes), ","))
	}

	// now fills with the server info
	vpn.PopulateServer(f)
}

// PeerPublicKeys returns a list of the public keys of the clients
func (vpn *WGVPN) PeerPublicKeys() []string {
	keys := make([]string, vpn.NumberOfPeers())
	for i, p := range vpn.peers {
		keys[i] = p.Public()
	}
	return keys
}

// ReservedIPs return a list of all the IP already reserved in
// the VPN
func (vpn *WGVPN) ReservedIPs() []net.IP {
	reserved := make([]net.IP, 0)
	// loop over the server addresses
	for _, n := range vpn.server.address {
		reserved = append(reserved, utils.CopyIP(n.IP))
	}
	// loop over the clients addresses
	for _, client := range vpn.peers {
		for _, n := range client.allowedIPs {
			reserved = append(reserved, utils.CopyIP(n.IP))
		}
	}
	return reserved
}

// ProvideNetworks generates a new slice (for a new client
// for example). It ensures that there is no overlap. An error
// is raised whan no ip are available
func (vpn *WGVPN) ProvideNetworks() ([]net.IPNet, error) {
	reserved := vpn.ReservedIPs()
	out := make([]net.IPNet, 0)
	// loop over the networks
	for _, n := range vpn.networks {
		// create a context with cancel for early termination
		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()

		// loop over the addresses within each network
		for ip := range utils.Iterate(ctx, &n) {
			// check if the ip is reserved
			// and if it is a special address
			special := ip.IsMulticast() || ip.IsUnspecified()
			if !special && utils.FindIP(ip, reserved) < 0 {
				// fmt.Println("IP:", ip)
				out = append(out, net.IPNet{
					IP:   ip,
					Mask: n.Mask,
				})

				// cancel the context to stop iteration
				cancel()
				break
			}
		}
	}
	return out, nil
}

// type addClientOptions struct {
// 	noPSK  bool
// 	dns    []net.IP
// 	routes []net.IPNet
// }

// type AddClientOption func(*addClientOptions)

// func WithoutPSK() AddClientOption {
// 	return func(options *addClientOptions) {
// 		options.noPSK = true
// 	}
// }

// func WithDNS(dns []net.IP) AddClientOption {
// 	return func(options *addClientOptions) {
// 		options.dns = dns
// 	}
// }

// func WithRoutes(routes []net.IPNet) AddClientOption {
// 	return func(options *addClientOptions) {
// 		options.routes = routes
// 	}
// }

// func (vpn *WGVPN) AddClient(options ...AddClientOption) (*WGClient, error) {
// 	ips, err := vpn.ProvideNetworks()
// 	if err != nil {
// 		return nil, err
// 	}

// 	opts := &addClientOptions{
// 		noPSK:  false,
// 		dns:    vpn.dns,
// 		routes: vpn.routes,
// 	}
// 	for _, o := range options {
// 		o(opts)
// 	}

// 	client := NewWGClient(ips, opts.noPSK, opts.dns)
// 	peer := client.ToPeer()
// 	vpn.peers = append(vpn.peers, peer)
// 	return client, nil
// }

func (vpn *WGVPN) AddClient(client *WGClient) error {
	ips, err := vpn.ProvideNetworks()
	if err != nil {
		return err
	}
	// assign provided ips to the client
	client.address = ips
	peer := client.ToPeer()
	vpn.peers = append(vpn.peers, peer)
	return nil
}

func (vpn *WGVPN) Log(event *zerolog.Event) *zerolog.Event {
	return event.
		Str("name", vpn.name).
		Str("endpoint", vpn.endpoint).
		Str("public_key", vpn.server.private.Public().Base64()).
		Uint16("port", vpn.server.port).
		Strs("networks", utils.StringifyNetworks(vpn.networks)).
		Strs("routes", utils.StringifyNetworks(vpn.routes)).
		Strs("dns", utils.StringifyIPs(vpn.dns)).
		Int("peers", vpn.NumberOfPeers())

}
